In [28]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

## Load The Dataset

In [29]:
fd = pd.read_csv('Daily Household Transactions.csv') ##fd means financial dashboard

## See the First 5 rows

In [30]:
fd.head()

,Date,Mode,Category,Subcategory,Note,Amount,Income/Expense,Currency
0,20/09/2018 12:04:08,Cash,Transportation,Train,2 Place 5 to Place 0,30.0,Expense,INR
1,20/09/2018 12:03:15,Cash,Food,snacks,Idli medu Vada mix 2 plates,60.0,Expense,INR
2,19/09/2018,Saving Bank account 1,subscription,Netflix,1 month subscription,199.0,Expense,INR
3,17/09/2018 23:41:17,Saving Bank account 1,subscription,Mobile Service Provider,Data booster pack,19.0,Expense,INR
4,16/09/2018 17:15:08,Cash,Festivals,Ganesh Pujan,Ganesh idol,251.0,Expense,INR

## See the Last 5 rows

In [31]:
fd.tail()

,Date,Mode,Category,Subcategory,Note,Amount,Income/Expense,Currency
2456,1/1/2015,Cash,Transportation,NaN,share jeep - Place T base to top,20.0,Expense,INR
2457,1/1/2015,Cash,Transportation,NaN,share auto - Place H to Place T base,20.0,Expense,INR
2458,1/1/2015,Cash,Transportation,NaN,bus - brc to Place H,30.0,Expense,INR
2459,1/1/2015,Cash,Food,NaN,tea,10.0,Expense,INR
2460,1/1/2015,Cash,Transportation,NaN,share auto - hospital to brc station,10.0,Expense,INR

## Dataset Shape

In [32]:
fd.shape

(2461, 8)

There are 10806 rowns and 7 columns

## Dataset columns

In [33]:
print("Columns:", fd.columns.tolist())

Columns: ['Date', 'Mode', 'Category', 'Subcategory', 'Note', 'Amount', 'Income/Expense', 'Currency']

## Dataset Data Type

In [34]:
fd.dtypes

Date               object
Mode               object
Category           object
Subcategory        object
Note               object
Amount            float64
Income/Expense     object
Currency           object
dtype: object

## Dataset Info

In [35]:
fd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2461 entries, 0 to 2460
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            2461 non-null   object
 1   Mode            2461 non-null   object
 2   Category        2461 non-null   object
 3   Subcategory     1826 non-null   object
 4   Note            1940 non-null   object
 5   Amount          2461 non-null   float64
 6   Income/Expense  2461 non-null   object
 7   Currency        2461 non-null   object
dtypes: float64(1), object(7)
memory usage: 153.9+ KB

## Statistical Analysis

In [36]:
fd.describe()

              Amount
count    2461.000000
mean     2751.145380
std     12519.615804
min         2.000000
25%        35.000000
50%       100.000000
75%       799.000000
max    250000.000000

## Missing Values Analysis

In [37]:
fd.isnull().sum()

Date                0
Mode                0
Category            0
Subcategory       635
Note              521
Amount              0
Income/Expense      0
Currency            0
dtype: int64

## Handle The missing Values

In [39]:
# Handle missing values
fd["Subcategory"] = fd["Subcategory"].fillna("Not Specified")

fd["Note"] = fd["Note"].fillna("No Note")

# Verify
fd.isnull().sum()

Date              0
Mode              0
Category          0
Subcategory       0
Note              0
Amount            0
Income/Expense    0
Currency          0
dtype: int64

## Duplicate Value Check

In [40]:
fd.duplicated().sum()

np.int64(9)

There are 9 duplicat values present in this dataset

In [42]:
## handle the duplicate values
fd = fd.drop_duplicates()
print("After removing duplicates, the shape of the DataFrame is:", fd.shape)

After removing duplicates, the shape of the DataFrame is: (2452, 8)