In [28]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

## Load The Dataset

In [29]:
fd = pd.read_csv('Daily Household Transactions.csv') ##fd means financial dashboard

## See the First 5 rows

In [30]:
fd.head()

,Date,Mode,Category,Subcategory,Note,Amount,Income/Expense,Currency
0,20/09/2018 12:04:08,Cash,Transportation,Train,2 Place 5 to Place 0,30.0,Expense,INR
1,20/09/2018 12:03:15,Cash,Food,snacks,Idli medu Vada mix 2 plates,60.0,Expense,INR
2,19/09/2018,Saving Bank account 1,subscription,Netflix,1 month subscription,199.0,Expense,INR
3,17/09/2018 23:41:17,Saving Bank account 1,subscription,Mobile Service Provider,Data booster pack,19.0,Expense,INR
4,16/09/2018 17:15:08,Cash,Festivals,Ganesh Pujan,Ganesh idol,251.0,Expense,INR

## See the Last 5 rows

In [31]:
fd.tail()

,Date,Mode,Category,Subcategory,Note,Amount,Income/Expense,Currency
2456,1/1/2015,Cash,Transportation,NaN,share jeep - Place T base to top,20.0,Expense,INR
2457,1/1/2015,Cash,Transportation,NaN,share auto - Place H to Place T base,20.0,Expense,INR
2458,1/1/2015,Cash,Transportation,NaN,bus - brc to Place H,30.0,Expense,INR
2459,1/1/2015,Cash,Food,NaN,tea,10.0,Expense,INR
2460,1/1/2015,Cash,Transportation,NaN,share auto - hospital to brc station,10.0,Expense,INR

## Dataset Shape

In [32]:
fd.shape

(2461, 8)

There are 10806 rowns and 7 columns

## Dataset columns

In [33]:
print("Columns:", fd.columns.tolist())

Columns: ['Date', 'Mode', 'Category', 'Subcategory', 'Note', 'Amount', 'Income/Expense', 'Currency']

## Dataset Data Type

In [34]:
fd.dtypes

Date               object
Mode               object
Category           object
Subcategory        object
Note               object
Amount            float64
Income/Expense     object
Currency           object
dtype: object

## Dataset Info

In [35]:
fd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2461 entries, 0 to 2460
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            2461 non-null   object
 1   Mode            2461 non-null   object
 2   Category        2461 non-null   object
 3   Subcategory     1826 non-null   object
 4   Note            1940 non-null   object
 5   Amount          2461 non-null   float64
 6   Income/Expense  2461 non-null   object
 7   Currency        2461 non-null   object
dtypes: float64(1), object(7)
memory usage: 153.9+ KB

## Statistical Analysis

In [36]:
fd.describe()

              Amount
count    2461.000000
mean     2751.145380
std     12519.615804
min         2.000000
25%        35.000000
50%       100.000000
75%       799.000000
max    250000.000000

## Missing Values Analysis

In [37]:
fd.isnull().sum()

Date                0
Mode                0
Category            0
Subcategory       635
Note              521
Amount              0
Income/Expense      0
Currency            0
dtype: int64

## Handle The missing Values

In [39]:
# Handle missing values
fd["Subcategory"] = fd["Subcategory"].fillna("Not Specified")

fd["Note"] = fd["Note"].fillna("No Note")

# Verify
fd.isnull().sum()

Date              0
Mode              0
Category          0
Subcategory       0
Note              0
Amount            0
Income/Expense    0
Currency          0
dtype: int64

## Duplicate Value Check

In [40]:
fd.duplicated().sum()

np.int64(9)

There are 9 duplicat values present in this dataset

In [42]:
## handle the duplicate values
fd = fd.drop_duplicates()
print("After removing duplicates, the shape of the DataFrame is:", fd.shape)

After removing duplicates, the shape of the DataFrame is: (2452, 8)

## Convert Data Types

In [43]:
fd["Date"] = pd.to_datetime(fd["Date"],format="mixed",dayfirst=True,errors="coerce")
# Convert Amount column
fd["Amount"] = pd.to_numeric(fd["Amount"],errors="coerce")
# Check data types
fd.dtypes

Date              datetime64[ns]
Mode                      object
Category                  object
Subcategory               object
Note                      object
Amount                   float64
Income/Expense            object
Currency                  object
dtype: object

## Validate Conversion

In [44]:
print("Invalid Dates:", fd["Date"].isnull().sum())
print("Invalid Amounts:", fd["Amount"].isnull().sum())

print("\nTransaction Types:")
print(fd["Income/Expense"].value_counts())

print("\nCurrencies:")
print(fd["Currency"].value_counts())

Invalid Dates: 0
Invalid Amounts: 0

Transaction Types:
Income/Expense
Expense         2173
Transfer-Out     154
Income           125
Name: count, dtype: int64

Currencies:
Currency
INR    2452
Name: count, dtype: int64

## Date-Based Feature Engineering

In [45]:
# Date Feature Engineering

fd["Year"] = fd["Date"].dt.year
fd["Month"] = fd["Date"].dt.month
fd["Month_Name"] = fd["Date"].dt.month_name()
fd["Day"] = fd["Date"].dt.day
fd["Day_of_Week"] = fd["Date"].dt.day_name()

fd["Year_Month"] = fd["Date"].dt.to_period("M")

# Check new features
fd.head()

,Date,Mode,Category,Subcategory,Note,Amount,Income/Expense,Currency,Year,Month,Month_Name,Day,Day_of_Week,Year_Month
0,2018-09-20 12:04:08,Cash,Transportation,Train,2 Place 5 to Place 0,30.0,Expense,INR,2018,9,September,20,Thursday,2018-09
1,2018-09-20 12:03:15,Cash,Food,snacks,Idli medu Vada mix 2 plates,60.0,Expense,INR,2018,9,September,20,Thursday,2018-09
2,2018-09-19 00:00:00,Saving Bank account 1,subscription,Netflix,1 month subscription,199.0,Expense,INR,2018,9,September,19,Wednesday,2018-09
3,2018-09-17 23:41:17,Saving Bank account 1,subscription,Mobile Service Provider,Data booster pack,19.0,Expense,INR,2018,9,September,17,Monday,2018-09
4,2018-09-16 17:15:08,Cash,Festivals,Ganesh Pujan,Ganesh idol,251.0,Expense,INR,2018,9,September,16,Sunday,2018-09

## Verify Features

In [46]:
print("Total Columns:", fd.shape[1])

print("\nDate Range:")
print("Start:", fd["Date"].min())
print("End:", fd["Date"].max())

print("\nMissing Values in New Features:")
print(
    fd[["Year", "Month", "Day", "Year_Month"]]
    .isnull().sum()
)

Total Columns: 14

Date Range:
Start: 2015-01-01 00:00:00
End: 2018-09-20 12:04:08

Missing Values in New Features:
Year          0
Month         0
Day           0
Year_Month    0
dtype: int64

## `Transaction Type Analysis`

In [47]:
# Transaction Type Analysis

transaction_summary = fd.groupby("Income/Expense")["Amount"].agg(["count", "sum", "mean"]).round(2)

transaction_summary

                count         sum      mean
Income/Expense
Expense          2173  1955380.53    899.85
Income            125  3042397.35  24339.18
Transfer-Out      154  1764780.90  11459.62

## `Financial KPI Calculation`

In [49]:
# Financial Dashboard - KPI Analysis

# 1. Total Income
total_income = fd.loc[fd["Income/Expense"] == "Income", "Amount"].sum()

# 2. Total Expense
total_expense = fd.loc[fd["Income/Expense"] == "Expense", "Amount"].sum()

# 3. Total Transfer-Out
total_transfer = fd.loc[fd["Income/Expense"] == "Transfer-Out", "Amount"].sum()

# 4. Net Surplus
net_surplus = total_income - total_expense

# 5. Savings Potential Rate
savings_rate = (net_surplus / total_income) * 100 if total_income > 0 else 0

# 6. Expense-to-Income Ratio
expense_ratio = (total_expense / total_income) * 100 if total_income > 0 else 0

# 7. Average Monthly Expense
total_months = fd["Year_Month"].nunique()
avg_monthly_expense = total_expense / total_months if total_months > 0 else 0

# 8. Average Expense Transaction
avg_transaction = fd.loc[fd["Income/Expense"] == "Expense", "Amount"].mean()

# Display Results
print("========== FINANCIAL DASHBOARD KPIs ==========")

print("Total Income:", round(total_income, 2))
print("Total Expense:", round(total_expense, 2))
print("Total Transfer-Out:", round(total_transfer, 2))
print("Net Surplus:", round(net_surplus, 2))

print("\n========== FINANCIAL RATIOS ==========")

print("Savings Potential Rate:", round(savings_rate, 2), "%")
print("Expense-to-Income Ratio:", round(expense_ratio, 2), "%")
print("Average Monthly Expense:", round(avg_monthly_expense, 2))
print("Average Expense Transaction:", round(avg_transaction, 2))

========== FINANCIAL DASHBOARD KPIs ==========
Total Income: 3042397.35
Total Expense: 1955380.53
Total Transfer-Out: 1764780.9
Net Surplus: 1087016.82

========== FINANCIAL RATIOS ==========
Savings Potential Rate: 35.73 %
Expense-to-Income Ratio: 64.27 %
Average Monthly Expense: 43452.9
Average Expense Transaction: 899.85

## Category-wise Expense Analysis