In [10]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

## Load The Dataset

In [13]:
fd = pd.read_csv('aug_personal_transactions_with_UserId.csv') ##fd means financial dashboard

## See the First 5 rows

In [14]:
fd.head()

,User ID,Date,Description,Amount,Transaction Type,Category,Account Name
0,2.0,1/1/2018,Amazon,11.11,debit,Shopping,Platinum Card
1,1.0,1/2/2018,Mortgage Payment,1247.44,debit,Mortgage & Rent,Checking
2,3.0,1/2/2018,Thai Restaurant,24.22,debit,Restaurants,Silver Card
3,2.0,1/3/2018,Credit Card Payment,2298.09,credit,Credit Card Payment,Platinum Card
4,2.0,1/4/2018,Netflix,11.76,debit,Movies & DVDs,Platinum Card

## See the Last 5 rows

In [15]:
fd.tail()

,User ID,Date,Description,Amount,Transaction Type,Category,Account Name
10801,NaN,04/13/2018,Italian Restaurant,124.31,credit,Credit Card Payment,Platinum Card
10802,NaN,01/25/2019,American Tavern,116.59,debit,Credit Card Payment,Platinum Card
10803,NaN,02/09/2020,Hardware Store,183.01,credit,Restaurants,Platinum Card
10804,NaN,05/24/2018,City Water Charges,124.90,debit,Home Improvement,Platinum Card
10805,NaN,09/02/2018,Hardware Store,91.19,debit,Movies & DVDs,Checking

## Dataset Shape

In [16]:
fd.shape

(10806, 7)

There are 10806 rowns and 7 columns

## Dataset columns

In [17]:
fd.columns

Index(['User ID', 'Date', 'Description', 'Amount', 'Transaction Type',
       'Category', 'Account Name'],
      dtype='object')

## Dataset Data Type

In [18]:
fd.dtypes

User ID             float64
Date                 object
Description          object
Amount              float64
Transaction Type     object
Category             object
Account Name         object
dtype: object

## Dataset Info